# Generated by Django 3.1.3 on 2020-12-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20201205_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='userf_profile',
            new_name='user_profile',
        ),
    ]
