# Generated by Django 3.1.3 on 2020-12-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20201205_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='userz_profile',
            new_name='user_profile',
        ),
    ]
